Pinned oslo.utils to 4.12.2
Cannot build cloudbase-init anymore due to a conflicting package version:

The conflict is caused by:
    oslo-utils 4.13.0 depends on pyparsing>=2.1.0
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
    The user requested (constraint) pyparsing===3.0.8